### ISSUE TITLE
End of client boundary

### ISSUE THREAD

**Issue by kiwi8sully** [ilya-zlobintsev/LACT#432] opened 2024-12-26 01:51 UTC
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation. Examples of known driver-side issues are fans not turning on with a custom curve or inaccurate power limits on RDNA3.
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

On upgradeing from 0.5.7 to testing 0.6.1 and rebooting the gui got into a state where error messages were spammed. 
**Screenshot taken at 12:59:02**
![cropped Screenshot from 2024-12-26 12-59-02](https://github.com/user-attachments/assets/89f06cc3-0070-4520-89c1-cb7b2eaab1e3)
I have not been able to reproduce this so I am guessing that it happened when adding a new profile based on the old "default". Or perhaps the damon needs to be reloaded when automatic switching is enabled.
The gui was killed by closing the main window.

Expected behavior;
One error message that can be killed without continuosly generating more. Ah the good old days of w98 ;)

[LACT-sysfs-snapshot-20241226-142420.tar.gz](https://github.com/user-attachments/files/18247950/LACT-sysfs-snapshot-20241226-142420.tar.gz)

### System info

```markdown
- LACT version:0.6.1 testing
- GPU model:5700XT
- Kernel version:6.12.6-x64v3-xanmod1 #0~20241220.g893acd0 SMP PREEMPT_DYNAMIC
- Distribution:Mint 21.3
```

**Comment by ilya-zlobintsev** [comment] 2024-12-26 10:27
The window spam is fixed with https://github.com/ilya-zlobintsev/LACT/commit/21df725c42b59ccad3490a558fb93c3ebc5ff65e.

Please let me know if you manage to reproduce the error (this error specifically will now just be logged though without error windows, as it happens due to background checking of the profile rules and not an explicit user action).

**Closed** 2024-12-26 11:34 UTC
