### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by saki2fifty** [ilya-zlobintsev/LACT#195] opened 2023-09-21 13:12 UTC
I've been using LACT for a while and haven't submitted anything... well, just beacuse.  :)

I script all my stuff out, but when I want to use the GUI to test some overclocking, I'm having a problem where certain things lock up or don't display properly.

On the first screenshot and when launching the gui, I simply select one of my gpu's and just locks up.  I have to ctrl-c it in the console to kill the session.

If I attempt again, go to OC and make a change (in this instance just change the GPU clock) and click "Apply", the window to "Yes/No" doesn't show anything, just blank.  This small window every now and then will display, but only a small percentage of the time will it show.  (2nd screenshot).

The 3rd screenshot is the console errors when I click "Apply".

![image](https://github.com/ilya-zlobintsev/LACT/assets/2228638/8794ec80-aedc-4ce4-afee-9e8c8c8e83cd)
![image](https://github.com/ilya-zlobintsev/LACT/assets/2228638/f9c69ede-5a47-486c-a141-e11938b2aabe)
![image](https://github.com/ilya-zlobintsev/LACT/assets/2228638/17c85a65-757c-4be5-9c1f-16b1f09376d4)

**Comment by saki2fifty** [comment] 2023-09-21 13:16
```
saki2fifty@sakkisminer01:~$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64         3.24.33-1ubuntu2          amd64        GTK graphical user interface library
ii  libgtk-3-bin             3.24.33-1ubuntu2          amd64        programs for the GTK graphical user interface library
ii  libgtk-3-common          3.24.33-1ubuntu2          all          common files for the GTK graphical user interface library
ii  libgtk-4-1:amd64         4.6.9+ds-0ubuntu0.22.04.1 amd64        GTK graphical user interface library
ii  libgtk-4-bin             4.6.9+ds-0ubuntu0.22.04.1 amd64        programs for the GTK graphical user interface library
ii  libgtk-4-common          4.6.9+ds-0ubuntu0.22.04.1 all          common files for the GTK graphical user interface library
ii  libgtk-4-dev:amd64       4.6.9+ds-0ubuntu0.22.04.1 amd64        development files for the GTK library
```

**Comment by saki2fifty** [comment] 2023-09-22 15:32
On this, i've narrowed it down to this.

If I run lact and keep the default GPU selected without changing, it works every time.

If I then change the gpu to any other gpu, make a change then Apply, then it locks up almost every time.

![image](https://github.com/ilya-zlobintsev/LACT/assets/2228638/26e2f833-b851-4268-8aff-230c49ef0e92)

![image](https://github.com/ilya-zlobintsev/LACT/assets/2228638/e8feec36-bde6-4b34-81f4-7974c94c8142)

Nothing at all in sys logs / dmesg.  Even when running RUST_BACKTRACE=1 lact

**Comment by ilya-zlobintsev** [comment] 2023-09-23 06:52
You seem to be running the GUI on windows via X11 forwarding? I'm not quite sure how gtk interacts with it, but one thing that could be causing it is the fact that the UI is blocked for a small amount of time when applying the settings, and over network it's a problem?

While I cannot reproduce the issue, I did make some changes that should help avoid blocking the GUI and also avoid some potential deadlocks. You can try the [test bulid](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build) and see if it solves the problem.

If it doesn't, then run `lact gui --log-level trace` and show the latest logs when it gets stuck.

**Comment by ilya-zlobintsev** [comment] 2024-02-04 22:16
I'm going to close this, feel free to reopen if the problem happens again

**Closed by ilya-zlobintsev** 2024-02-04 22:16 UTC
