### ISSUE TITLE
Implement fan_zero_rpm sysfs interface

### ISSUE THREAD

**Issue by lichtmetzger** [ilya-zlobintsev/LACT#392] opened 2024-10-26 23:00 UTC
@wylfen has kindly submitted a [patch](https://gitlab.freedesktop.org/drm/amd/-/issues/3489#note_2626120) that makes it possible to turn off the 0rpm feature on RDNA3 cards.

I've tested it on my RX7800XT and it works. However, when doing any change in LACT, it always reverts it to the default state and I have to run:
```
echo '0' | sudo tee /sys/class/drm/card2/device/gpu_od/fan_ctrl/fan_zero_rpm
echo 'c' | sudo tee /sys/class/drm/card2/device/gpu_od/fan_ctrl/fan_zero_rpm
```
again to make it work.

I know it's not official (yet), but maybe you can add support for this in LACT? 😊

**Comment by ilya-zlobintsev** [comment] 2024-10-27 07:53
Yeah this is promising, I've mentioned it in https://github.com/ilya-zlobintsev/LACT/issues/255#issuecomment-2439443147 already. I could try implementing it right now, but you'd have to test it as I do not have a system with RDNA3 and an ability to install a patched kernel currently.

**Comment by ilya-zlobintsev** [comment] 2024-10-27 08:11
Could you post the contents of the `fan_zero_rpm` file?

**Comment by wylfen** [comment] 2024-10-27 09:24
`fan_zero_rpm` behaves like the other files in `gpu_od/`, it will report the current setting and available range when read from:

```
FAN_ZERO_RPM:
0
OD_RANGE:
ZERO_RPM: 0 1
```

I'd assume that this design stays once upstreamed, but obviously can't give any guarantees. I'll poke the mailing list about an update sometime soon, too.

**Comment by ilya-zlobintsev** [comment] 2024-10-27 15:03
#393 adds support for this, if it works as intended I'll merge it once the kernel patch is accepted upstream.

**Comment by lichtmetzger** [comment] 2024-10-27 22:48
Thank your for the quick implementation! It works well on my card.

**Comment by JosephM0on** [comment] 2024-10-28 08:37
Hello
I have AMD RADEON RX 7800 XT, how can I do to test?

**Comment by ilya-zlobintsev** [comment] 2024-10-28 18:04
> Hello I have AMD RADEON RX 7800 XT, how can I do to test?

This currently requires compiling a patched kernel and building LACT from the `pmfw-zero-rpm` branch.

For general usage that doesn't require tinkering you'll need to wait until the kernel patch is accepted.

**Comment by JosephM0on** [comment] 2024-10-28 18:47
> > Hello I have AMD RADEON RX 7800 XT, how can I do to test?
> 
> This currently requires compiling a patched kernel and building LACT from the `pmfw-zero-rpm` branch.
> 
> For general usage that doesn't require tinkering you'll need to wait until the kernel patch is accepted.

Thank you very much, I will wait without any problem, keep up the good work

**Comment by wylfen** [comment] 2024-10-30 10:44
I don't know how long this will take to land, but the patch series [has been reviewed](https://lists.freedesktop.org/archives/amd-gfx/2024-October/116354.html) now. We now also have another setting, `fan_zero_rpm_stop_temperature`.

**Comment by ilya-zlobintsev** [comment] 2024-10-30 11:08
> I don't know how long this will take to land, but the patch series [has been reviewed](https://lists.freedesktop.org/archives/amd-gfx/2024-October/116354.html) now. We now also have another setting, `fan_zero_rpm_stop_temperature`.

That sounds like a useful feature as well, I'll add it once it is merged in case there will be more interface changes.

**Comment by ilya-zlobintsev** [comment] 2024-11-07 12:31
I've updated the PR with the new parameter name and added a fan stop temperature option. I will merge it when someone is able to confirm that it is working.

**Closed** 2024-11-13 22:11 UTC

**Comment by ilya-zlobintsev** [comment] 2024-11-13 22:15
This has been merged, and you can use it if you run a recent `linux-next` kernel. It will land in 6.13 if running a stable version.
