### ISSUE TITLE
Error setting voltage

### ISSUE THREAD

**Issue by SoiledBrush** [ilya-zlobintsev/LACT#212] opened 2023-11-24 13:34 UTC
![Screenshot from 2023-11-24 19-32-22](https://github.com/ilya-zlobintsev/LACT/assets/43366389/962a050c-cf88-4e63-91c7-357b99f2d5f3)

On RX 5500XT
amdgpu.ppfeaturemask=0xffffffff enabled.

**Comment by ilya-zlobintsev** [comment] 2023-11-24 13:53
What's the output of `cat /sys/class/drm/card*/device/pp_od_clk_voltage`?

**Comment by SoiledBrush** [comment] 2023-11-24 15:28
`cat /sys/class/drm/card*/device/pp_od_clk_voltage
OD_SCLK:
0: 500Mhz
1: 1825Mhz
OD_MCLK:
1: 900MHz
OD_VDDC_CURVE:
0: 500MHz 710mV
1: 1162MHz 794mV
2: 1825MHz 1115mV
OD_RANGE:
SCLK:     800Mhz       2200Mhz
MCLK:     625Mhz        930Mhz
VDDC_CURVE_SCLK[0]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[0]:     700mV        1150mV
VDDC_CURVE_SCLK[1]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[1]:     700mV        1150mV
VDDC_CURVE_SCLK[2]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[2]:     700mV        1150mV
`
Voltage control works on corectrl

**Comment by hejsekvojtech** [comment] 2023-11-26 13:46
Set performance level to MANUAL

**Comment by eFISHncy** [comment] 2023-12-09 01:10
Im getting the same error if i want to change the min or max voltage points.
Using a RX 5700XT (50th anniversary ed.).
amdgpu.ppfeaturemask=0xffffffff is enabled.
Voltage control works without any issues on corectrl

`cat /sys/class/drm/card*/device/pp_od_clk_voltage` outputs:

```
OD_SCLK:
0: 800Mhz
1: 2064Mhz
OD_MCLK:
1: 875MHz
OD_VDDC_CURVE:
0: 800MHz 718mV
1: 1432MHz 818mV
2: 2064MHz 1201mV
OD_RANGE:
SCLK:     800Mhz       2200Mhz
MCLK:     625Mhz        950Mhz
VDDC_CURVE_SCLK[0]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[0]:     750mV        1200mV
VDDC_CURVE_SCLK[1]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[1]:     750mV        1200mV
VDDC_CURVE_SCLK[2]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[2]:     750mV        1200mV
```

**Comment by BluewyWork** [comment] 2023-12-16 13:25
I have the same problem with the RX 5700XT

**Comment by BluewyDiamond** [comment] 2023-12-16 13:31
I have the same problem with the RX 5700XT

**Comment by ilya-zlobintsev** [comment] 2023-12-20 21:08
Should be fixed now, please try latest commit (either via the [test build](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build) or using the `lact-git` AUR package on Arch)

**Comment by eFISHncy** [comment] 2023-12-21 00:10
I tried the lact-git AUR package (The LACT gui now reports version 0.5.1-release for the daemon and the gui).
Now the voltage **and** frequency points can't be changed.
With the older version (0.5.0) i could change at least the frequency points.
If i try to save changed voltage or clock points i get the following error in both cases:

```
Could not apply settings
Caused by:
    0: Could not commit clocks settings
    1: Got error from daemon: Could not apply settings: Could not write clocks table: io error: Invalid argument (os error 22)
```

**Comment by ilya-zlobintsev** [comment] 2023-12-21 08:44
https://github.com/ilya-zlobintsev/LACT/commit/1a12316cfe0245d45815f19406e5b8bd5a4e6913 should help, please try updating again (and make sure to restart the daemon, this time there isn't a version change)

**Comment by ilya-zlobintsev** [comment] 2023-12-21 17:30
Does the configuration work when running these commands manually? (Adjust values for your specific GPU, `s` is core clock, `m` is memory)
```
echo 's 0 850' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
echo 's 1 2150' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
echo 'm 1 950' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
echo 'vc 0 850 711' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
echo 'vc 1 1450 801' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
echo 'vc 2 2150 1200' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
echo 'c' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
```

**Comment by BluewyDiamond** [comment] 2023-12-21 19:35
> Does the configuration work when running these commands manually? (Adjust values for your specific GPU, `s` is core clock, `m` is memory)
> 
> ```
> echo 's 0 850' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> echo 's 1 2150' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> echo 'm 1 950' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> echo 'vc 0 850 711' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> echo 'vc 1 1450 801' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> echo 'vc 2 2150 1200' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> echo 'c' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage
> ```
> 
> Also, the latest commit will now provide more detailed error messages

```
bash script.bash
s 0 850
s 1 2100
m 1 950
vc 0 850 711
tee: /sys/class/drm/card0/device/pp_od_clk_voltage: Invalid argument
vc 1 1450 801
vc 2 2100 1120
c
```
![2023-12-21T20:32:00,902095575+01:00](https://github.com/ilya-zlobintsev/LACT/assets/115411576/1e83f048-b255-484c-b13b-793242b4cff2)

**Comment by BluewyDiamond** [comment] 2023-12-21 20:37
It seems that the command echo 'vc 0 800 710' | sudo tee /sys/class/drm/card*/device/pp_od_clk_voltage is not working as expected on my end. This issue may be the reason behind the error displayed by the daemon.

I'm uncertain why corectrl isn't encountering a problem with this. It could be that corectrl is either not applying this specific line `vc 0 800 710`, or it might be failing silently only for that line while successfully applying other configurations.

**Comment by ilya-zlobintsev** [comment] 2023-12-21 21:03
@BluewyDiamond do the kernel logs (in `dmesg`) say anything about this? 
I have a suspicion that this might be caused by the default curve having voltage points that are actually outside of the GPU's configurable range, causing them to fail to get reapplied. If this is the case, there should be a message in the logs.

**Comment by eFISHncy** [comment] 2023-12-22 01:25
Did a quick update to the newest lact-git aur package

I think its the correct suspicion. The default values are outside of the allowed range.

Whatever value (voltage or frequency) i want to change im getting this error in the kernel log:
```
amdgpu 0000:0c:00.0: amdgpu: OD setting (3, 718) is less than the minimum allowed (750)
```

CoreCtrl is giving me a whole bunch of those errors when im using the _stock_ default profile:
```
[ 1801.866420] amdgpu 0000:0c:00.0: amdgpu: OD setting (3, 718) is less than the minimum allowed (750)
[ 1909.505062] amdgpu 0000:0c:00.0: amdgpu: OD setting (3, 718) is less than the minimum allowed (750)
[ 1944.701550] amdgpu 0000:0c:00.0: amdgpu: OD setting (3, 718) is less than the minimum allowed (750)
[ 1944.701561] amdgpu 0000:0c:00.0: amdgpu: OD setting (3, 718) is less than the minimum allowed (750)
[ 1944.701799] amdgpu 0000:0c:00.0: amdgpu: OD setting (7, 1201) is greater than the maximum allowed (1200)
[ 1944.701805] amdgpu 0000:0c:00.0: amdgpu: OD setting (7, 1201) is greater than the maximum allowed (1200)

```
The stock profile is equivalent to the following `cat /sys/class/drm/card*/device/pp_od_clk_voltage` output:
```
OD_SCLK:
0: 800Mhz
1: 2064Mhz
OD_MCLK:
1: 875MHz
OD_VDDC_CURVE:
0: 800MHz 718mV
1: 1432MHz 819mV
2: 2064MHz 1201mV
OD_RANGE:
SCLK:     800Mhz       2200Mhz
MCLK:     625Mhz        950Mhz
VDDC_CURVE_SCLK[0]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[0]:     750mV        1200mV
VDDC_CURVE_SCLK[1]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[1]:     750mV        1200mV
VDDC_CURVE_SCLK[2]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[2]:     750mV        1200mV
```

When im activating the advanced options in CoreCtrl and enable the manual voltage control without altering any values im getting no errors in the kernel log.
With this profile im getting the following `cat /sys/class/drm/card*/device/pp_od_clk_voltage` output:
```
OD_SCLK:
0: 800Mhz
1: 2064Mhz
OD_MCLK:
1: 875MHz
OD_VDDC_CURVE:
0: 800MHz 750mV
1: 1432MHz 819mV
2: 2064MHz 1200mV
OD_RANGE:
SCLK:     800Mhz       2200Mhz
MCLK:     625Mhz        950Mhz
VDDC_CURVE_SCLK[0]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[0]:     750mV        1200mV
VDDC_CURVE_SCLK[1]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[1]:     750mV        1200mV
VDDC_CURVE_SCLK[2]:     800Mhz       2200Mhz
VDDC_CURVE_VOLT[2]:     750mV        1200mV
```
=> both the minimum and maximum voltage values of the default curve are outside of the allowed range.

**Comment by ilya-zlobintsev** [comment] 2023-12-22 08:37
The voltage values will now be normalized to be within the allowed range. This should (hopefully) finally fix the issue

**Comment by BluewyDiamond** [comment] 2023-12-23 11:07
> The voltage values will now be normalized to be within the allowed range. This should (hopefully) finally fix the issue

Your commit did the trick, and everything's working smoothly now. Thanks a ton!

**Closed** 2023-12-23 11:20 UTC
