### ISSUE TITLE
Rdna 3 support

### ISSUE THREAD

**Issue by nex86** [ilya-zlobintsev/LACT#384] opened 2024-10-04 20:59 UTC
Upgraded from rx6600 to 7600.
Cant control fans now..
Lact is on the latest version and kernel is on 6.9

**Comment by ilya-zlobintsev** [comment] 2024-10-05 11:25
Do you have overclocking enabled? It's required for fan control on RDNA3, there should be a message about it.

Also see the [hardware support](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) info.

**Comment by shenk-i** [comment] 2024-10-05 15:28
I want to add this too, RX 7800 XT was never able to control fans manually, and the GPU is always 0 RPM until the GPU just decides when the fans turn on, and then, maybe it will use your curve. What I do now is i set LACT fan control to Automatic with these settings:

![Screenshot_20241005_172337](https://github.com/user-attachments/assets/163d6532-fbad-4ec0-90e6-74fb9123ad8a)

At least with these settings the fans dont just jump to almost max, but they will gradually increase speed, BUT still they will turn on more-or-less around 70C at the VRAM, or at 75C Junction. Honestly this is quite frustrating since on Windows with MSI Afterburner manual fan control works fine, I have my own curve, and I can keep my VRAM and Junction temps below 70 at almost all times.

**Comment by ilya-zlobintsev** [comment] 2024-10-05 15:33
> the GPU is always 0 RPM until the GPU just decides when the fans turn on, and then, maybe it will use your curve

This is known behaviour caused by the driver, and it is documented in the hardware support info:

> There is an unconfigurable temperature threshold below which the fan does not get turned on, even with a custom curve.

**Comment by shenk-i** [comment] 2024-10-05 16:49
yeah thought so, i guess i was hoping that it would've been resolved by now

**Comment by sddearjack** [comment] 2024-10-08 15:37
Iljuh, iam Also experiencing same problem. Fedora 41(beta) 6.11.2-300.fc41.x86_64. Just switched from rtx 3070 few days ago to 7900xtx nitro+. Kernel parameter is enabled for Overclocking, undervolting works well. But manual fan control is not working. I have seen it is limited on the frontpage of LACT github. My issue is, that when I use the curve section to set fan speed it applies but fan RPM stays 0rpm. When the edge or junction idk atm goes above 60C fans will automatically kick in. I think that is amdgpu driver issue, not the LACT.

**Comment by ilya-zlobintsev** [comment] 2024-10-25 20:40
I'm going to close this as the original issue has not enough info to go off, and the other comments are mentioning a known driver-side limitation.

**Closed by ilya-zlobintsev** 2024-10-25 20:40 UTC

**Comment by lichtmetzger** [comment] 2024-10-26 23:04
> I think that is amdgpu driver issue, not the LACT.

That's true and there's a patch available here. It implements a sysfs interface to turn off the 0rpm feature:
https://gitlab.freedesktop.org/drm/amd/-/issues/3489#note_2626120

It's not officially landed in the kernel yet, so you'd have to build it yourself. I've tested it on my 7800XT and it works reliably.

Maybe LACT can also support it in the future (see #392 )
