### ISSUE TITLE
Unable to change Power Level Mode since 0.5.4

### ISSUE THREAD

**Issue by DreamingCuttlefish** [ilya-zlobintsev/LACT#346] opened 2024-07-02 00:23 UTC
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

Since 0.5.4, I've been unable to change the Power Level Mode. After changing the performance level to "manual" I then select "COMPUTE" for instance, but as soon as I hit "Apply" it reverts back to "BOOTUP_DEFAULT". This did not happen on 0.5.3. 

[LACT-sysfs-snapshot-20240701-202043.tar.gz](https://github.com/user-attachments/files/16060092/LACT-sysfs-snapshot-20240701-202043.tar.gz)

### System info

```markdown
- LACT version: 0.5.4
- GPU model: Radeon RX 6950xt
- Kernel version: 6.9.6
- Distribution: Bazzite (Fedora Atomic)
```

**Comment by ilya-zlobintsev** [comment] 2024-07-02 06:44
Duplicate of #312 , fixed in latest master (you can try the [test release](https://github.com/ilya-zlobintsev/LACT/releases/tag/test-build))

**Comment by Atemu** [comment] 2024-07-16 11:09
Would it be possible to create a hotfix for this? I think it's quite a critical bug.

**Comment by ilya-zlobintsev** [comment] 2024-07-18 15:52
> Would it be possible to create a hotfix for this? I think it's quite a critical bug.

Done: https://github.com/ilya-zlobintsev/LACT/releases/tag/v0.5.5

**Closed by ilya-zlobintsev** 2024-07-18 15:52 UTC

**Comment by Atemu** [comment] 2024-07-18 17:16
Thanks a bunch!
