### ISSUE TITLE
OC settings not being applied if fan control is used at the same time

### ISSUE THREAD

**Issue by flippette** [ilya-zlobintsev/LACT#345] opened 2024-07-01 13:55 UTC
### Checklist

- [X] The problem is not listed in the [hardware support matrix](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#hardware-support) as a known limitation
- [X] I've included a [debug snapshot](https://github.com/ilya-zlobintsev/LACT?tab=readme-ov-file#reporting-issues) if the issue is related to hardware configuration

### Bug description

When only using the OC functionality, settings are applied as normal:

![image](https://github.com/ilya-zlobintsev/LACT/assets/43138244/7ce08861-0b4d-4149-b9d6-88863159ae46)

When fan control is also used, OC settings are suddenly no longer applying (note the memory clock dropping from 1300 to 1218MHz here):

![image](https://github.com/ilya-zlobintsev/LACT/assets/43138244/40904591-ea64-4b23-8011-f013c3311a6f)

I've talked about this problem already [here](https://gitlab.freedesktop.org/drm/amd/-/issues/2402#note_2208252). TL;DR, I suspect the order in which settings are written is causing the problem.

qlum on that thread doesn't seem to be able to reproduce the problem, but I consistently can, on multiple distros, distro installs, and kernels.

On my hardware, this custom script seems to work:

```sh
#!/usr/bin/env bash

CARD_ID=card1
HWMON_ID=hwmon3

PL=280
SCLK_MAX=3200
MCLK_MAX=1300
VOLT_OFF=-75
TEMP_TGT=70

GPU_SYSFS="/sys/class/drm/$CARD_ID/device"
HWMON_SYSFS="$GPU_SYSFS/hwmon/$HWMON_ID"
FANCTRL_SYSFS="$GPU_SYSFS/gpu_od/fan_ctrl"

echo "$((PL * 10**6))" > "$HWMON_SYSFS/power1_cap"

echo "s 1 $SCLK_MAX" > "$GPU_SYSFS/pp_od_clk_voltage"
echo "m 1 $MCLK_MAX" > "$GPU_SYSFS/pp_od_clk_voltage"
echo "vo $VOLT_OFF" > "$GPU_SYSFS/pp_od_clk_voltage"

echo "$TEMP_TGT" > "$FANCTRL_SYSFS/fan_target_temperature"

# commit both `pp_od_clk_voltage` and `fan_target_temperature` _AFTER_ setting everything
echo "c" | tee "$GPU_SYSFS/pp_od_clk_voltage" | tee "$FANCTRL_SYSFS/fan_target_temperature"
```

(yes I know this isn't an issue with LACT per se, but it'd be great to circumvent the issue now instead of having to wait for an amdgpu fix)

Debug snapshots:

[OC only](https://github.com/user-attachments/files/16053882/LACT-sysfs-snapshot-20240701-205317.tar.gz)
[OC & fan control](https://github.com/user-attachments/files/16053871/LACT-sysfs-snapshot-20240701-205159.tar.gz)

### System info

```markdown
- LACT version: 0.4.5-release
- GPU model: Sapphire Nitro+ 7800 XT
- Kernel version: 6.9.6-zen1
- Distribution: NixOS 24.11 unstable
```

**Comment by ilya-zlobintsev** [comment] 2024-07-01 15:10
Duplicate of #329, should be fixed in latest master.

**Comment by flippette** [comment] 2024-07-01 15:22
I'll go ahead and close this issue then. Thank you!

**Closed** 2024-07-01 15:23 UTC
